runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php

- url: /bower_components
  static_dir: bower_components


- url: /dist
  static_dir: dist


- url: /(.*)$
  script: \1



env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:dbname=lear;unix_socket=/cloudsql/cloud-test-1-192422:us-central1:cloud1
  MYSQL_USER: rachid
  MYSQL_PASSWORD: rachid